name = "photos-blog"
account_id = "3e196b8605fd883dfcee5cdb5dd106cc"
workers_dev = false
route = "photos.butou.ma/*"
compatibility_date = "2023-11-21"
main = "workers-site/index.js"
[site]
bucket = "./dist"